import AnimationBuilder from "./animation-builder.js";

const timelineSlider = document.querySelector("#timeline-slider");
const playButtonTimeline = document.querySelector(".play-animation");
const animationControls = document.querySelectorAll(".animation-control");
const canvas = document.querySelector(".canvas");
const downloadButton = document.querySelector(".download");

// Create the animationbuilder with the given container to animate with a default timeline of 5 seconds
const animationBuilder = new AnimationBuilder(canvas, 5);

// Load in the JSON data from a file (TODO: later this should become user controllable)
animationBuilder.loadAnimation("./scripts/animation.json");

// When the animation automatically plays the slider updates on the progress of the animation duration
animationBuilder.setOnUpdateListener((timeline) => {
  timelineSlider.value = timeline.progress() * 100;
});

// Connect all sliders to te animation builder
animationControls.forEach((control) => {
  control.addEventListener("input", (event) => {
    // Gather slider property and value
    const propertyName = event.target.dataset.property;
    const value = parseFloat(event.target.value); /* Todo: Should not be float for all values*/

    // Set a new keyframe for the given property with the given value
    animationBuilder.setKeyframe("el-1", propertyName, value); /* Todo: do not hardcode .el-1*/
  });
});

// Allow to scrub through the timeline
timelineSlider.addEventListener("input", (e) => {
  const progress = e.target.value / 100;
  animationBuilder.setProgress(progress);
});

// Connect the play/pause button with the animationBuilder
playButtonTimeline.addEventListener("click", () => {
  const isPaused = animationBuilder.isPaused();
  playButtonTimeline.textContent = isPaused ? "Pause" : "play";
  animationBuilder.togglePlay();
});

// Download data
downloadButton.addEventListener("click", () => {
  const timelineData = animationBuilder.getAnimationData();
  const downloadData = generateIndex(timelineData);
  downloadFile(downloadData, "index.html");

})

// Source:
// https://coreui.io/answers/how-to-download-a-file-in-javascript/
function downloadFile(data, filename, type = 'text/html') {
    const blob = new Blob([data], { type })
    const url = URL.createObjectURL(blob)

    const link = document.createElement('a')
    link.href = url
    link.download = filename
    document.body.appendChild(link)
    link.click()

    document.body.removeChild(link)
    URL.revokeObjectURL(url)
}

// Generated by ChatGPT
function generateIndex(timelineData, durationSeconds = 4) {
  return `<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8" />
  <title>GSAP Animation</title>

  <script src="https://cdn.jsdelivr.net/npm/gsap@3.12.5/dist/gsap.min.js"></script>

  <style>
    html, body {
      margin: 0;
      padding: 0;
      width: 100vw;
      height: 100vh;
      overflow: hidden;
    }

    #canvas {
      width: 100vw;
      height: 100vh;
      position: relative;
    }

    h1 {
      position: absolute;
      margin: 0;
    }
  </style>
</head>

<body>
  <div id="canvas"></div>

  <script>
    const timelineData = ${JSON.stringify(timelineData, null, 2)};

    class AnimationBuilder {
      constructor(canvas, durationSeconds) {
        this.canvas = canvas;
        this.durationSeconds = durationSeconds;

        this.timelineData = {
          elements: [],
          animations: [],
        };

        this.timeline = gsap.timeline({
          paused: true,
          repeat: -1,
        });
      }

      buildAnimation() {
        const currentProgress = this.timeline.progress() || 0;
        this.timeline.clear();

        this.buildElements();
        this.buildAnimations();

        this.timeline.progress(currentProgress);
      }

      buildElements() {
        const elementsData = this.timelineData.elements;

        this.canvas.innerHTML = "";

        elementsData.forEach((elementData) => {
          const element = document.createElement("h1");
          element.classList.add(elementData.group, elementData.id);
          element.textContent = elementData.content;

          this.canvas.appendChild(element);
        });
      }

      buildAnimations() {
        this.timelineData.animations.forEach((animationData) => {
          const target = animationData.target;

          animationData.properties.forEach((propertyData) => {
            const property = propertyData.property;
            const keyframes = propertyData.keyframes;

            keyframes.sort((a, b) => a.progress - b.progress);

            if (keyframes.length === 1) {
              gsap.set("." + target, {
                [property]: keyframes[0].value,
              });
              return;
            }

            for (let i = 1; i < keyframes.length; i++) {
              let last = keyframes[i - 1];
              let current = keyframes[i];

              let timeDifferenceSeconds =
                (current.progress - last.progress) * this.durationSeconds;

              this.timeline.to(
                "." + target,
                {
                  [property]: current.value,
                  duration: timeDifferenceSeconds,
                  ease: current.ease ? current.ease : "none",
                },
                last.progress * this.durationSeconds
              );
            }
          });
        });
      }
    }

    const canvas = document.getElementById("canvas");

    const builder = new AnimationBuilder(canvas, ${durationSeconds});

    builder.timelineData = timelineData;
    builder.buildAnimation();

    builder.timeline.play();
  </script>
</body>
</html>`;
}